### ISSUE TITLE
"Not a content pack" error when installing HG 4.0 on blender 4

### ISSUE THREAD

**Issue by deepglugs** [OliverJPost/HumGen3D#104]
**Describe the bug**
I'm unable to install any content packs on HG 4.0.16 on Blender 4.0
![image](https://github.com/OliverJPost/HumGen3D/assets/70453896/482a8d1a-a52a-4c21-91e1-36e3d1c8eaa3)

I downloaded the content packs and plugin from blendermarket at the same time.

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Blender Version 4.0
 - Human Generator Version 4.0.16

**Comment by OliverJPost** [comment]
Is there a possibility the downloaded file has a hidden `.zip` extension? The "Not a content pack" error can only occur when the file path does not end with `hgpack`

**Comment by deepglugs** [comment]
They are definitely .hgpack: `
``bash
~/Downloads% ls *.hg*
Base_Clothes_V4_1.hgpack  Base_Hair_V4_1.hgpack  Base_Humans_V4_1.hgpack  Base_Poses_V4_0.hgpack
```

**Comment by deepglugs** [comment]
I see the relevant code that checks for "hgpack".  I wonder if something is screwy with my setup after upgrading from HG 3.0.  I'll dig some more.

**Comment by OliverJPost** [comment]
@deepglugs Was the issue resolved in the end or are you still facing it?
