### ISSUE TITLE
Error when Generating New Human (Blender 4.2)

### ISSUE THREAD

**Issue by ilkersatir** [OliverJPost/HumGen3D#114]
When i try to generate new Human, i get an Error.

![image](https://github.com/user-attachments/assets/15e4ec4b-2817-4c95-b2cb-e3ca1002f4cb)

Using System
WIndows 11
Blender : 4.2
Human Generator Version:  4.0.18

**Comment by Breezy-y** [comment]
I had the same problem in blender 4.2
you can open the \Blender Foundation\Blender\4.2\scripts\addons\HumGen3D\common\render.py
change the line 15  (context.scene.render.engine = "BLENDER_EEVEE")
to(context.scene.render.engine = "BLENDER_EEVEE_NEXT")
Can fix error 
![Quicker_20240718_183425](https://github.com/user-attachments/assets/af69a113-01b4-4882-b237-806baadcfd32)

**Comment by ilkersatir** [comment]
Thanks @Breezy-y . this Solved my Problem.

i did this

`# Copyright (c) 2022 Oliver J. Post & Alexander Lashko - GNU GPL V3.0, see LICENSE

"""Module for functions related to Blender's render engines Cycles and Eevee"""

import bpy

def set_eevee_ao_and_strip(context: bpy.types.Context) -> None:
    """Set Eevee's AO and strip settings to the best looking configuration for hair.

    Args:
        context (bpy.types.Context): Blender context
    """
    current_render_engine = str(context.scene.render.engine)
    
    try:
        context.scene.render.engine = "BLENDER_EEVEE"
        if context.scene.render.engine != "BLENDER_EEVEE":
            raise ValueError("BLENDER_EEVEE not available, switching to BLENDER_EEVEE_NEXT")
    except (ValueError, TypeError):
        context.scene.render.engine = "BLENDER_EEVEE_NEXT"
    
    if context.scene.render.engine == "BLENDER_EEVEE" or context.scene.render.engine == "BLENDER_EEVEE_NEXT":
        context.scene.eevee.use_gtao = True
        context.scene.render.hair_type = "STRIP"
    
    # Restore the original render engine
    context.scene.render.engine = current_render_engine
`

**Comment by OliverJPost** [comment]
This issue was addressed in the latest version v4.0.20
