### ISSUE TITLE
human.clothing.outfit.remove() does not refresh the masks

### ISSUE THREAD

**Issue by iperov** [OliverJPost/HumGen3D#120]
**Describe the bug**
human.clothing.outfit.remove() does not refresh body masks

current workaround is to use private method:
```
masks = human.clothing.outfit.remove()
human.clothing.outfit._set_geometry_masks(masks, [])
```

**To Reproduce**
1. add cloth
2. call `human.clothing.outfit.remove()`

**Screenshots**
![blender_2024-09-14_17-34-17](https://github.com/user-attachments/assets/939d8094-ab7e-4109-818e-7d46a64899d5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version 4.2.1
 - Human Generator Version 4.0.21

**Comment by OliverJPost** [comment]
Expected behaviour would be for the geometry masks to be removed by `outfit.remove()` or for a public `remove_geometry masks` method?

**Comment by iperov** [comment]
I think assuming `human.clothing.outfit.remove()` is public user api method, thus this func should remove cloth and update visual

**Comment by OliverJPost** [comment]
Made the method remove masks by default, keeping the original functionality behind the `remove_masks=False` flag
