### ISSUE TITLE
Lower teeth constraint is not updated on human duplication

### ISSUE THREAD

**Issue by OliverJPost** [OliverJPost/HumGen3D#124]
<img width="336" alt="CleanShot 2024-10-20 at 00 42 37@2x" src="https://github.com/user-attachments/assets/a41ae71e-d8e3-40da-b6b8-be623cc69e72">

**Comment by Googey1** [comment]
Sorry what does this mean. I've encountered the problem with the teeth being misplaced when duplicating a  human mesh using the addon. I've downloaded the most up to date version f the addon but the problem is still there. What needs doing please?

**Comment by OliverJPost** [comment]
The problem has been solved in the internal version of HG. This fix has not yet been released as an official update, but if you already want to get the fix you can get it by updating to "main", see the "Update to main" part of this guide https://help.humgen3d.com/update
