### ISSUE TITLE
Does not work in command line mode

### ISSUE THREAD

**Issue by dalbom** [OliverJPost/HumGen3D#13]
Hi,

When I tried to make humans from a python script while running blender in the background mode, the addon outputs some error messages.

Firstly,
Error: Object ‘HG_Body’ not in collection ‘Scene Collection’
and similar errors also for other meshes

Then another error message
Error: Vertex not in group
shows up for thousand times.

My Blender is 3.2.2 and the script is based on the HG_Human API set. The command was:
blender -b empty_scene.blend -P generate_human.py

**Comment by OliverJPost** [comment]
Could you share the full error text from the console (`Window>Show system console` if you're on Windows) and (if applicable) the part of your script that causes the error messages to appear?

**Comment by dalbom** [comment]
Hi, Thank you for your swift response :)

Attached you can find the error message, the entire code, and the scene screenshot. Hope it helps!

[test_generate_human.txt](https://github.com/OliverJPost/HumGen3D/files/9374884/test_generate_human.txt)

[error.txt](https://github.com/OliverJPost/HumGen3D/files/9374886/error.txt)

Oh I can't upload screenshot here...

**Comment by OliverJPost** [comment]
I'm not able to reproduce the error on my end using your script. Does the script still correctly produce generated humans or does it totally fail? (P.s. sorry for the late reply)

**Comment by dalbom** [comment]
Hi, no worries. it's not an urgent issue because the script runs well when the Blender is running in foreground mode. 

So it works if I use
`blender empty_scene.blend -P generate_human.py`

but doesn't work with
`blender **-b** empty_scene.blend -P generate_human.py`

From the error messages, it seems like the script at least tried to generate a human:

> Error: Object 'HG_Cary_Backup' not in collection 'Scene Collection'
> Error: Object 'HG_Body.001' not in collection 'Scene Collection'
> Error: Object 'HG_Eyes.001' not in collection 'Scene Collection'
> Error: Object 'HG_TeethLower.001' not in collection 'Scene Collection'
> Error: Object 'HG_TeethUpper.001' not in collection 'Scene Collection'

But those objects are not assigned to a collection and vertices are not assigned to a group:
> Error: Vertex not in group
> Error: Vertex not in group
> ...
> Error: Vertex not in group
> Error: Vertex not in group

And the rendering call doesn't produce any image.

Can you confirm you tested the script in the background mode? If so, I could try to save the blender file after generating humans.

**Comment by OliverJPost** [comment]
I tested it in foreground mode, will run further tests in background mode!

**Comment by OliverJPost** [comment]
Can you see if this is still an issue in the new V4 API? We rewrote it from scratch

**Comment by OliverJPost** [comment]
Closed due to inactivity
