### ISSUE TITLE
Batch mode hangs blender

### ISSUE THREAD

**Issue by photojourneyman** [OliverJPost/HumGen3D#29]
I am trying to get batch mode working but even at the simplest settings, it appears to hang blender. I have waited for up to 9 minutes and the progress Building human 1 still shows 0%.   I have tried re-installing the plug-in and re-setting the file path.  I have tried it in Blender 3.3.0 and 3.3.1.  I am using a 2 year old desktop PC running windows 10 and Nvidia cards.  
![image](https://user-images.githubusercontent.com/88125078/195466964-b91ae8d8-f510-43bd-acd1-2c0ddc7126d5.png)

**Comment by OliverJPost** [comment]
We are aware of this issue happening for some users and it has been fixed in the upcoming version of Human Generator!

**Comment by OliverJPost** [comment]
Should be fixed in new V4 release
