### ISSUE TITLE
Hair and pants missing in Blender 3.4 and HG 3

### ISSUE THREAD

**Issue by radman-x** [OliverJPost/HumGen3D#41]
**Describe the bug**
Hair and pants missing in Blender 3.4 and HG 3

**To Reproduce**
1. Open Blender v3.4.0. Delete default cube.
2. Open HG v3 via vertical add-on tab
3. Choose Asian1 from asset browser.
4. Click "Generate New Human".
5. Human is missing hair and pants (see screen shot below).

**Screenshots**
![image](https://user-images.githubusercontent.com/9258904/206560261-4608262c-a732-4bb0-a811-200300d728aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version v3.4.0
 - Human Generator Version v3

**Comment by OliverJPost** [comment]
What exactly do you mean that it's missing hair and pants? In HG V3 starting humans were created without hair or clothing, or am I misunderstanding the report? The screenshot seems to show a human already in finalise phase, is this directly after creation?

**Comment by radman-x** [comment]
Screenshot was missing hair and underpants; I thought HG v3 had them, even in the create phase. I will rerun all these test cases with your latest beta and Blender 3.4 on Monday and report results.

**Comment by radman-x** [comment]
Blender v3.4 + HG v4.beta.6 shows hair (but no pants). This may not be a bug, so closing this (you can re-open if v4 should display underpants in "Solid" shading mode).
![image](https://user-images.githubusercontent.com/9258904/207983802-3bd90327-5c5f-4b8f-9f9e-db552cb8c3dd.png)

Also, hair and pants are displayed in "Material Preview" shading mode:
![image](https://user-images.githubusercontent.com/9258904/207983997-3d5edeaa-038d-4049-9873-ab5c30b5c53f.png)
