### ISSUE TITLE
Problem baking texture in blender 3.4.1

### ISSUE THREAD

**Issue by jack18-1866** [OliverJPost/HumGen3D#44]
Hi,
I get a error when I try to bake (Rendering texture 16/17 at 88%):

Python: Traceback (most recent call last):
  File "/Users/jaak/Library/Application Support/Blender/3.4/scripts/addons/HumGen3D/features/utility_section/HG_BAKE.py", line 127, in modal
    assert img
AssertionError

How to fix?
Thanks.

**Comment by OliverJPost** [comment]
I am not exactly sure what is causing this issue, but it should be fixed in V4. We are working on releasing the final version of V4 in the near future
